# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Win2.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QPushButton,
    QSizePolicy, QSlider, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(744, 266)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 70, 141, 21))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.gen1 = QComboBox(Form)
        self.gen1.setObjectName(u"gen1")
        self.gen1.setGeometry(QRect(30, 40, 131, 21))
        self.gen1.setEditable(False)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 20, 141, 21))
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.gen2 = QComboBox(Form)
        self.gen2.setObjectName(u"gen2")
        self.gen2.setGeometry(QRect(30, 90, 131, 21))
        self.gen2.setEditable(False)
        self.gen3 = QComboBox(Form)
        self.gen3.setObjectName(u"gen3")
        self.gen3.setGeometry(QRect(30, 140, 131, 21))
        self.gen3.setEditable(False)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 120, 141, 21))
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.horizontalSlider = QSlider(Form)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(540, 40, 160, 22))
        self.horizontalSlider.setMaximum(2)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QSlider.TicksBelow)
        self.btn_start = QPushButton(Form)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(580, 200, 131, 51))
        self.ethn2 = QComboBox(Form)
        self.ethn2.setObjectName(u"ethn2")
        self.ethn2.setGeometry(QRect(180, 90, 141, 21))
        self.ethn2.setEditable(False)
        self.ethn3 = QComboBox(Form)
        self.ethn3.setObjectName(u"ethn3")
        self.ethn3.setGeometry(QRect(180, 140, 141, 21))
        self.ethn3.setEditable(False)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(180, 70, 161, 21))
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.ethn1 = QComboBox(Form)
        self.ethn1.setObjectName(u"ethn1")
        self.ethn1.setGeometry(QRect(180, 40, 141, 21))
        self.ethn1.setEditable(False)
        self.ethn1.setMaxVisibleItems(2)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(180, 120, 161, 21))
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 20, 161, 21))
        self.label_12.setFont(font)
        self.label_12.setWordWrap(True)
        self.role1 = QComboBox(Form)
        self.role1.setObjectName(u"role1")
        self.role1.setGeometry(QRect(340, 40, 141, 21))
        self.role1.setEditable(False)
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(340, 20, 161, 21))
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.role2 = QComboBox(Form)
        self.role2.setObjectName(u"role2")
        self.role2.setGeometry(QRect(340, 90, 141, 21))
        self.role2.setEditable(False)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(340, 70, 161, 21))
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.role3 = QComboBox(Form)
        self.role3.setObjectName(u"role3")
        self.role3.setGeometry(QRect(340, 140, 141, 21))
        self.role3.setEditable(False)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(340, 120, 161, 21))
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(540, 20, 171, 21))
        self.label_16.setFont(font)
        self.label_16.setWordWrap(True)
        self.horizontalSlider_2 = QSlider(Form)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(540, 90, 160, 22))
        self.horizontalSlider_2.setMaximum(2)
        self.horizontalSlider_2.setSliderPosition(2)
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QSlider.TicksBelow)
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(540, 70, 171, 21))
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.horizontalSlider_3 = QSlider(Form)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setGeometry(QRect(540, 140, 160, 22))
        self.horizontalSlider_3.setMaximum(2)
        self.horizontalSlider_3.setSliderPosition(1)
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QSlider.TicksBelow)
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(540, 120, 171, 21))
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 220, 521, 31))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.label_10.setFont(font1)
        self.label_10.setWordWrap(True)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Character 2 Gender:", None))
        self.gen1.setCurrentText("")
        self.label_5.setText(QCoreApplication.translate("Form", u"Character 1 Gender:", None))
        self.gen2.setCurrentText("")
        self.gen3.setCurrentText("")
        self.label_7.setText(QCoreApplication.translate("Form", u"Character 3 Gender:", None))
        self.btn_start.setText(QCoreApplication.translate("Form", u"Start Game", None))
        self.ethn2.setCurrentText("")
        self.ethn3.setCurrentText("")
        self.label_9.setText(QCoreApplication.translate("Form", u"Character 2 Ethnicity:", None))
        self.ethn1.setCurrentText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"Character 3 Ethnicity:", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Character 1 Ethnicity:", None))
        self.role1.setCurrentText("")
        self.label_13.setText(QCoreApplication.translate("Form", u"Character 1 Role:", None))
        self.role2.setCurrentText("")
        self.label_14.setText(QCoreApplication.translate("Form", u"Character 2 Role:", None))
        self.role3.setCurrentText("")
        self.label_15.setText(QCoreApplication.translate("Form", u"Character 3 Role:", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Character 1 Temperment:", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Character 2 Temperment:", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Character 3 Temperment:", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"*Temperment Scale: Left - Happy, Right - Angry, Middle - neutral.", None))
    # retranslateUi

